blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('kategori/<slug:kategoriInput>/', views.detail_kategori, name='kategoriArtikel'),
    path('detail/<slug:slugInput>/', views.detail_artikel, name='detailArtikel'),
]

kontak/urls.py
from django.urls import path

from . import views

app_name = 'kontak'
urlpatterns = [
    path('', views.index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('kontak/', include('kontak.urls', namespace='kontak')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Kategori(models.Model):
    nama = models.CharField(max_length=255)
    slugKategori =models.SlugField(editable=False, blank=True)

    def save(self, *args, **kwargs):
        self.slugKategori = slugify(self.nama)
        return super(Kategori, self).save(*args, **kwargs)

    def __str__(self):
        return "{}. {}".format(self.id, self.nama)


class Artikel(models.Model):
    judul = models.CharField(max_length=255)
    isi = models.TextField()
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE)
    slugArtikel = models.SlugField(editable=False, blank=True)
    publicDate = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slugArtikel = slugify(self.judul)
        return super(Artikel, self).save(*args, **kwargs)

    def __str__(self):
        return "{}. {}".format(self.id, self.judul)

kontak/models.py
from django.db import models

# Create your models here.

kontak/forms.py
from django import forms
import datetime


JENIS_KELAMIN = (
    ('p','Pria'),
    ('w','Wanita'),
)

TAHUN = range(1, datetime.date.today().year+1, 1)
today = datetime.date.today()
MONTHYEAR = datetime.date(today.year, today.month, 1)


class KontakForms(forms.Form):
    nama = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control'
            }
        )
    )
    email = forms.EmailField(
        help_text='Masukan Email Anda Dengan Benar.'
    )
    jenkel = forms.ChoiceField(
        widget = forms.RadioSelect(
            attrs= {
                'class':'from-check-input',
            }
        ), 
        choices = JENIS_KELAMIN, 
        label = 'Jenis Kelamin',
    )
    tgl_lahir = forms.DateField(
        initial=MONTHYEAR,
        widget = forms.SelectDateWidget(
            years=TAHUN,
            attrs= {
                'class':'form-select mb-2'
            },
        ),
    )
    pesan = forms.CharField(
        widget=forms.Textarea(
            attrs= {
                'class':'form-control'
            }
        )
    )
    agree = forms.BooleanField()

    email.widget.attrs.update({'class':'form-control',})

blog/views.py
from django.shortcuts import render

# Create your views here.
from .models import Artikel, Kategori

def index(request):
    articles = Artikel.objects.all()
    allKategori = Kategori.objects.all()[:6]

    context = {
        'title':'Blog',
        'heading':'Selamat Datang Di Halaman Blog',
        'Articles': articles,
        'category': allKategori,
    }
    return render(request, 'blog.html', context)


def detail_kategori(request, kategoriInput):
    articles = Artikel.objects.filter(kategori__nama=kategoriInput)

    context = {
        'title':'Kategori Article',
        'heading':'Selamat Datang Di Halaman Kategori: ' + kategoriInput.capitalize(),
        'Articles': articles,
    }
    return render(request, 'kategori.html', context)


def detail_artikel(request, slugInput):
    detail_article = Artikel.objects.get(slugArtikel=slugInput)
    allKategori = Kategori.objects.all()[:8]

    context = {
        'title':'Detail Article',
        'heading':'Selamat Datang Di Halaman Detail',
        'DetailArticle': detail_article,
        'category': allKategori,
    }
    return render(request, 'detail.html', context)

kontak/views.py
from django.shortcuts import render

from .forms import KontakForms

# Create your views here.
def index(request):
    kontak_form = KontakForms()
    context = {
        'title':'Kontak',
        'heading':'Kontak Form',
        'f_kontak':kontak_form,
    }
    print(request.POST)
    return render(request, 'kontak.html', context)

mysite/views.py
from django.shortcuts import render


def index(request):
    context = {
        'title':'Home',
        'heading':'Selamat Datang Di Halaman Home',
    }
    return render(request, 'index.html', context)

blog/templates/blog.html
{% extends "base.html" %}

{% block head_title %}
    {{title}}
{% endblock head_title %}


{% block contents %}
    <h1 class="mt-3">{{heading}}</h1>

    <ul class="list-group list-group-horizontal">
        {% for categories in category %}
            <li class="list-group-item"><a class="text-decoration-none" href="{% url 'blog:kategoriArtikel' categories.nama %}">{{categories.nama|capfirst}}</a></li>
        {% endfor %}
    </ul>

    <div class="row">
        {% for post in Articles %}
        <div class="col-md-4 g-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{post.judul}}</h5>
                    <span>{{post.publicDate}}</span>
                    <br>
                    <span class="badge text-bg-primary">{{post.kategori.nama|capfirst}}</span>
                    <p class="card-text">{{post.isi|truncatewords:25}}<p>
                    <a type="button" href="{% url 'blog:detailArtikel' post.slugArtikel %}" class="btn btn-primary">View More</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock contents %}

blog/templates/detail.html
{% extends "base.html" %}

{% block head_title %}
    {{title}}
{% endblock head_title %}


{% block contents %}
    <div class="row mt-5">
        <div class="col-md-8">
            <h5 class="card-title">{{DetailArticle.judul}}</h5>
            <span>{{DetailArticle.publicDate}}</span>
            <br>
            <span class="badge text-bg-primary">{{DetailArticle.kategori.nama|capfirst}}</span>
            <p class="card-text">{{DetailArticle.isi}}<p>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Kategori
                </div>
                <ul class="list-group list-group-flush">
                    {% for categories in category %}
                        <li class="list-group-item"><a class="text-decoration-none" href="{% url 'blog:kategoriArtikel' categories.nama %}">{{categories.nama|capfirst}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

{% endblock contents %}

blog/templates/kategori.html
{% extends "base.html" %}

{% block head_title %}
    {{title}}
{% endblock head_title %}


{% block contents %}
    <h1 class="mt-3">{{heading}}</h1>
    <div class="row">
        {% for post in Articles %}
        <div class="col-md-4 g-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{post.judul}}</h5>
                    <span>{{post.publicDate}}</span>
                    <br>
                    <span class="badge text-bg-primary">{{post.kategori.nama|capfirst}}</span>
                    <p class="card-text">{{post.isi|truncatewords:25}}<p>
                    <a type="button" href="{% url 'blog:detailArtikel' post.slugArtikel %}" class="btn btn-primary">View More</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock contents %}

kontak/templates/kontak.html
{% extends "base.html" %}


{% block head_title %}
    {{title}}
{% endblock head_title %}

{% block contents %}
    <h1 class="mt-3">{{heading}}</h1>

    <form method="POST">
        {% csrf_token %}

        <div class="mb-3">
            {{f_kontak.nama.label_tag}}
            {{f_kontak.nama}}
        </div>
        <div class="mb-3">
            {{f_kontak.email.label_tag}}
            {{f_kontak.email}}
            <div class="form-text">
                {{f_kontak.email.help_text}}
            </div>
        </div>
        <div class="mb-3">
            {{f_kontak.jenkel.label_tag}}
            {% for komp_jenkel in f_kontak.jenkel %}
                <div class="form-check">
                    {{komp_jenkel.tag}}
                    <label for="{{komp_jenkel.id_for_label}}">
                        {{komp_jenkel.choice_label}}
                    </label>
                </div>
            {% endfor %}
        </div>
        <div class="mb-3">
            {{f_kontak.tgl_lahir.label_tag}}
            {{f_kontak.tgl_lahir}}
        </div>
        <div class="mb-3">
            {{f_kontak.pesan.label_tag}}
            {{f_kontak.pesan}}
        </div>
        <div class="mb-3">
            <div class="form-check">
                {{f_kontak.agree}}
                <label for="{{f_kontak.agree.id_for_label}}" class="form-check-label">
                    {{f_kontak.agree.label}}
                </label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Kirim</button>
    </form>

{% endblock contents %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block head_title %}
            {{title}}
        {% endblock head_title %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

    {% include 'snippets/navbar.html' %}

    <div class="container">
        {% block contents %}

        {% endblock contents %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}


{% block head_title %}
    {{title}}
{% endblock head_title %}

{% block contents %}
    <h1 class="mt-3">{{heading}}</h1>
{% endblock contents %}

templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg bg-body-secondary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Yabsir Aditya</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="ms-auto navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'kontak:index' %}">Kontak</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
            </ul>
        </div>
    </div>
</nav>